# fly.toml configuration

# Confirm health checks and exposed port compatibility
[health_checks]
  interval = "10s"
  timeout = "2s"
  grace_period = "30s"
  path = "/health"
  protocol = "http"
  check_interval = "10s"
  check_timeout = "2s"

[processes]
  [[processes.app]]
    port = "8080"
    cmd = "start"